// s1 to s7
export const PART_1 = [
  // SECTION 1
  { id: "s1_1", name_ar: "رز أبيض مطبوخ", category: "نشويات", carbs_per_100g: 28, min: 25, max: 32, avg: 28, is_weighable: true, aliases: ["رز","أرز","رز ابيض"] },
  { id: "s1_2", name_ar: "رز بني", category: "نشويات", carbs_per_100g: 23, min: 20, max: 26, avg: 23, is_weighable: true, aliases: ["رز بني","أرز بني"] },
  { id: "s1_3", name_ar: "مكرونة مطبوخة", category: "نشويات", carbs_per_100g: 25, min: 22, max: 28, avg: 25, is_weighable: true, aliases: ["مكرونة","باستا"] },
  { id: "s1_4", name_ar: "بطاطس مسلوقة", category: "نشويات", carbs_per_100g: 20, min: 17, max: 23, avg: 20, is_weighable: true, aliases: ["بطاطس","بطاطا"] },
  { id: "s1_5", name_ar: "بطاطس مقلية", category: "نشويات", carbs_per_100g: 35, min: 30, max: 40, avg: 35, is_weighable: true, aliases: ["بطاطس مقلية","فرنش فرايز"] },
  { id: "s1_6", name_ar: "شوفان", category: "نشويات", carbs_per_100g: 66, min: 60, max: 70, avg: 66, is_weighable: true, aliases: ["شوفان","أوفز"] },
  { id: "s1_7", name_ar: "برغل مطبوخ", category: "نشويات", carbs_per_100g: 19, min: 16, max: 22, avg: 19, is_weighable: true, aliases: ["برغل"] },
  { id: "s1_8", name_ar: "شعير مطبوخ", category: "نشويات", carbs_per_100g: 28, min: 24, max: 32, avg: 28, is_weighable: true, aliases: ["شعير"] },
  { id: "s1_9", name_ar: "ذرة مسلوقة", category: "نشويات", carbs_per_100g: 19, min: 16, max: 22, avg: 19, is_weighable: true, aliases: ["ذرة"] },

  // SECTION 2
  { id: "s2_1", name_ar: "خبز عربي أبيض", category: "خبز ومعجنات", carbs_per_100g: 55, avg: 55, is_weighable: true, aliases: ["خبز عربي","خبز","عيش"] },
  { id: "s2_2", name_ar: "خبز عربي أسمر", category: "خبز ومعجنات", carbs_per_100g: 50, avg: 50, is_weighable: true, aliases: ["خبز أسمر"] },
  { id: "s2_3", name_ar: "توست أبيض", category: "خبز ومعجنات", carbs_per_100g: 49, avg: 49, is_weighable: true, aliases: ["توست"] },
  { id: "s2_4", name_ar: "توست أسمر", category: "خبز ومعجنات", carbs_per_100g: 41, avg: 41, is_weighable: true, aliases: ["توست أسمر"] },
  { id: "s2_5", name_ar: "صامولي", category: "خبز ومعجنات", carbs_per_100g: 50, avg: 50, is_weighable: true, aliases: ["صامولي","خبز صامولي"] },
  { id: "s2_6", name_ar: "كرواسون", category: "خبز ومعجنات", carbs_per_100g: 45, avg: 45, is_weighable: true, aliases: ["كرواسون"] },
  { id: "s2_7", name_ar: "فطيرة جبن", category: "خبز ومعجنات", carbs_per_100g: 30, avg: 30, is_weighable: true, aliases: ["فطيرة جبن"] },
  { id: "s2_8", name_ar: "فطيرة زعتر", category: "خبز ومعجنات", carbs_per_100g: 35, avg: 35, is_weighable: true, aliases: ["فطيرة زعتر","مناقيش زعتر"] },
  { id: "s2_9", name_ar: "بيتزا", category: "خبز ومعجنات", carbs_per_100g: 30, avg: 30, is_weighable: true, aliases: ["بيتزا"] },
  { id: "s2_10", name_ar: "مناقيش", category: "خبز ومعجنات", carbs_per_100g: 40, avg: 40, is_weighable: true, aliases: ["مناقيش"] },
  { id: "s2_11", name_ar: "توست أبيض المراعي", category: "خبز ومعجنات", carbs_per_100g: 0, is_weighable: false, unit_options: [{name: "شريحة", carbs: 15}] },
  { id: "s2_12", name_ar: "توست أسمر المراعي", category: "خبز ومعجنات", carbs_per_100g: 0, is_weighable: false, unit_options: [{name: "شريحة", carbs: 12}] },
  { id: "s2_13", name_ar: "توست حبوب المراعي", category: "خبز ومعجنات", carbs_per_100g: 0, is_weighable: false, unit_options: [{name: "شريحة", carbs: 13}] },
  { id: "s2_14", name_ar: "توست عائلي المراعي", category: "خبز ومعجنات", carbs_per_100g: 0, is_weighable: false, unit_options: [{name: "شريحتين", carbs: 30}] },
  { id: "s2_15", name_ar: "خبز برجر المراعي", category: "خبز ومعجنات", carbs_per_100g: 0, is_weighable: false, unit_options: [{name: "حبة", carbs: 28}] },
  { id: "s2_16", name_ar: "خبز برجر أسمر المراعي", category: "خبز ومعجنات", carbs_per_100g: 0, is_weighable: false, unit_options: [{name: "حبة", carbs: 26}] },
  { id: "s2_17", name_ar: "خبز برجر كبير المراعي", category: "خبز ومعجنات", carbs_per_100g: 0, is_weighable: false, unit_options: [{name: "2 حبة", carbs: 56}] },
  { id: "s2_18", name_ar: "خبز تورتيلا المراعي", category: "خبز ومعجنات", carbs_per_100g: 0, is_weighable: false, unit_options: [{name: "حبة", carbs: 20}] },
  { id: "s2_19", name_ar: "خبز صامولي أسمر المراعي", category: "خبز ومعجنات", carbs_per_100g: 0, is_weighable: false, unit_options: [{name: "حبة", carbs: 35}] },
  { id: "s2_20", name_ar: "خبز هوت دوق المراعي", category: "خبز ومعجنات", carbs_per_100g: 0, is_weighable: false, unit_options: [{name: "حبة", carbs: 26}] },
  { id: "s2_21", name_ar: "خبز هوت دوق كبير المراعي", category: "خبز ومعجنات", carbs_per_100g: 0, is_weighable: false, unit_options: [{name: "2 حبة", carbs: 52}] },
  { id: "s2_22", name_ar: "صامولي بر المراعي", category: "خبز ومعجنات", carbs_per_100g: 0, is_weighable: false, unit_options: [{name: "حبة", carbs: 35}] },
  { id: "s2_23", name_ar: "صامولي عائلي المراعي", category: "خبز ومعجنات", carbs_per_100g: 0, is_weighable: false, unit_options: [{name: "2 حبة", carbs: 60}] },
  { id: "s2_24", name_ar: "خبز بر لورين", category: "خبز ومعجنات", carbs_per_100g: 0, is_weighable: false, unit_options: [{name: "رغيف", carbs: 28}] },
  { id: "s2_25", name_ar: "خبز حبوب لورين", category: "خبز ومعجنات", carbs_per_100g: 0, is_weighable: false, unit_options: [{name: "رغيف", carbs: 28}] },
  { id: "s2_26", name_ar: "خبز عائلي لورين", category: "خبز ومعجنات", carbs_per_100g: 0, is_weighable: false, unit_options: [{name: "2 رغيف", carbs: 60}] },
  { id: "s2_27", name_ar: "خبز عربي لورين", category: "خبز ومعجنات", carbs_per_100g: 0, is_weighable: false, unit_options: [{name: "رغيف", carbs: 30}] },

  // SECTION 3
  { id: "s3_1", name_ar: "تمر سكري", category: "تمر وسكريات", carbs_per_100g: 75, avg: 75, is_weighable: true, unit_options: [{name: "3 حبات", carbs: 20}, {name: "5 حبات", carbs: 35}, {name: "7 حبات", carbs: 48}] },
  { id: "s3_2", name_ar: "تمر سكري فاخر", category: "تمر وسكريات", carbs_per_100g: 75, avg: 75, is_weighable: true, unit_options: [{name: "3 حبات", carbs: 22}] },
  { id: "s3_3", name_ar: "تمر خلاص", category: "تمر وسكريات", carbs_per_100g: 75, avg: 75, is_weighable: true, unit_options: [{name: "3 حبات", carbs: 21}, {name: "5 حبات", carbs: 36}, {name: "7 حبات", carbs: 49}] },
  { id: "s3_4", name_ar: "تمر خلاص فاخر", category: "تمر وسكريات", carbs_per_100g: 75, avg: 75, is_weighable: true, unit_options: [{name: "3 حبات", carbs: 23}] },
  { id: "s3_5", name_ar: "تمر عجوة", category: "تمر وسكريات", carbs_per_100g: 75, avg: 75, is_weighable: true, unit_options: [{name: "3 حبات", carbs: 22}, {name: "5 حبات", carbs: 38}, {name: "7 حبات", carbs: 50}] },
  { id: "s3_6", name_ar: "تمر عجوة فاخر", category: "تمر وسكريات", carbs_per_100g: 75, avg: 75, is_weighable: true, unit_options: [{name: "3 حبات", carbs: 24}] },
  { id: "s3_7", name_ar: "تمر خضري", category: "تمر وسكريات", carbs_per_100g: 75, avg: 75, is_weighable: true, unit_options: [{name: "3 حبات", carbs: 22}, {name: "5 حبات", carbs: 35}, {name: "7 حبات", carbs: 48}] },
  { id: "s3_8", name_ar: "تمر صفري", category: "تمر وسكريات", carbs_per_100g: 75, avg: 75, is_weighable: true, unit_options: [{name: "3 حبات", carbs: 21}, {name: "5 حبات", carbs: 34}, {name: "7 حبات", carbs: 47}] },
  // ... (leaving out standard sugars except general)
  { id: "s3_9", name_ar: "سكر أبيض", category: "تمر وسكريات", carbs_per_100g: 100, avg: 100, is_weighable: true },
  { id: "s3_10", name_ar: "سكر بني", category: "تمر وسكريات", carbs_per_100g: 98, avg: 98, is_weighable: true },
  { id: "s3_11", name_ar: "عسل", category: "تمر وسكريات", carbs_per_100g: 82, avg: 82, is_weighable: true },
  { id: "s3_12", name_ar: "دبس تمر", category: "تمر وسكريات", carbs_per_100g: 75, avg: 75, is_weighable: true },

  // SECTION 4
  { id: "s4_1", name_ar: "تفاح", category: "فواكه", carbs_per_100g: 14, min: 12, max: 16, avg: 14, is_weighable: true, aliases: ["تفاح"] },
  { id: "s4_2", name_ar: "موز", category: "فواكه", carbs_per_100g: 23, min: 20, max: 26, avg: 23, is_weighable: true, aliases: ["موز"] },
  { id: "s4_3", name_ar: "برتقال", category: "فواكه", carbs_per_100g: 12, min: 10, max: 14, avg: 12, is_weighable: true, aliases: ["برتقال"] },
  { id: "s4_4", name_ar: "عنب", category: "فواكه", carbs_per_100g: 18, min: 16, max: 20, avg: 18, is_weighable: true, aliases: ["عنب"] },
  { id: "s4_5", name_ar: "بطيخ", category: "فواكه", carbs_per_100g: 8, min: 6, max: 10, avg: 8, is_weighable: true, aliases: ["بطيخ","حبحب"] },
  { id: "s4_6", name_ar: "شمام", category: "فواكه", carbs_per_100g: 8, min: 6, max: 10, avg: 8, is_weighable: true, aliases: ["شمام"] },
  { id: "s4_7", name_ar: "أناناس", category: "فواكه", carbs_per_100g: 13, min: 11, max: 15, avg: 13, is_weighable: true, aliases: ["أناناس"] },
  { id: "s4_8", name_ar: "مانجو", category: "فواكه", carbs_per_100g: 15, min: 13, max: 17, avg: 15, is_weighable: true, aliases: ["مانجو"] },

  // SECTION 7
  { id: "s7_1", name_ar: "كبسة دجاج", category: "وجبات عربية", carbs_per_100g: 15, avg: 15, min: 12, max: 18, is_weighable: true },
  { id: "s7_2", name_ar: "كبسة لحم", category: "وجبات عربية", carbs_per_100g: 14, avg: 14, min: 11, max: 17, is_weighable: true },
  { id: "s7_3", name_ar: "مندي", category: "وجبات عربية", carbs_per_100g: 13, avg: 13, min: 10, max: 16, is_weighable: true },
  { id: "s7_4", name_ar: "حنيذ", category: "وجبات عربية", carbs_per_100g: 11, avg: 11, min: 8, max: 14, is_weighable: true },
  { id: "s7_5", name_ar: "قرصان", category: "وجبات عربية", carbs_per_100g: 30, avg: 30, min: 25, max: 35, is_weighable: true },
  { id: "s7_6", name_ar: "معصوب", category: "وجبات عربية", carbs_per_100g: 35, avg: 35, min: 30, max: 45, is_weighable: true },
  { id: "s7_7", name_ar: "عريكة", category: "وجبات عربية", carbs_per_100g: 50, avg: 50, min: 40, max: 60, is_weighable: true },
  { id: "s7_8", name_ar: "حنيني", category: "وجبات عربية", carbs_per_100g: 38, avg: 38, min: 30, max: 50, is_weighable: true },
  { id: "s7_9", name_ar: "كشري", category: "وجبات عربية", carbs_per_100g: 30, avg: 30, min: 25, max: 35, is_weighable: true },
  { id: "s7_10", name_ar: "مجبوس", category: "وجبات عربية", carbs_per_100g: 24, avg: 24, min: 20, max: 28, is_weighable: true }
]
